#!/bin/sh
#
# $Id$
#
# Utility script to rebuild configure script.
#
# Copyright 1992-2021 Deven T. Corzine <deven@ties.org>
#
# SPDX-License-Identifier: MIT
#

aclocal --force --install && autoheader --force && automake --add-missing && autoconf --force
