#!/bin/sh
#
# $Id$
#
# Utility script to rebuild configure script.
#
# Copyright 1992-2003 by Deven T. Corzine.  All rights reserved.
#
# This file is part of the Phoenix conferencing system.
#
# This file may be distributed under the terms of the Q Public License
# as defined by Trolltech AS of Norway (except for Choice of Law) and as
# appearing in the file LICENSE.QPL included in the packaging of this file.
#
# This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
# WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
# Visit <http://www.phoenix-cmc.org/license/> or contact <info@phoenix-cmc.org>
# for more information or if any conditions of this licensing are unclear.
#

aclocal --force --install && autoheader --force && automake --add-missing && autoconf --force
