#!/bin/sh
#
# $Id: bootstrap,v 1.3 2003/02/24 06:57:48 deven Exp $
#
# Utility script to rebuild configure script.
#
# Copyright 1992-2021 Deven T. Corzine <deven@ties.org>
#
# SPDX-License-Identifier: MIT
#

aclocal --force --install && autoheader --force && automake --add-missing && autoconf --force
