[package]
name          = "phoenix_cmc"
version       = "0.1.0"
authors       = ["Deven T. Corzine <deven@ties.org>"]
edition       = "2021"
description   = "Conferencing system server supporting real-time communication between users, currently using a text-based user interface over the standard TELNET protocol, so no special client program is necessary for users."
documentation = "https://docs.rs/phoenix_cmc"
readme        = "README.md"
homepage      = "https://phoenix-cmc.org/"
repository    = "https://github.com/deven/phoenix/"
license       = "MIT"
keywords      = ["cmc", "chat", "conferencing", "im", "instant message"]

[dependencies]
anyhow             = "1.0.57"
bytes              = "1.1.0"
structopt          = "0.3.26"
tokio              = { version = "1.19.2", features = ["full"] }
tracing            = "0.1.35"
tracing-subscriber = "0.3.11"
