#!/bin/sh
#
# $Id: checkin,v 1.7 2000/03/22 06:07:47 deven Exp $
#
# Conferencing system server -- RCS checkin script.
#
# Copyright 1992-1996, 2000 by Deven T. Corzine.  All rights reserved.
#

stty erase '^h'
for x in $*; do
   if [ ! -f $x ]; then
      co $x
      rcstouch $x
   fi
   if [ -f $x ]; then
      rcs -u $x >/dev/null 2>&1
      chmod u+w $x
      if rcsdiff $x >/dev/null 2>&1; then
         echo "$x is current."
      else
         y="`ls -l $x`"
         (ls -l $x; rcsdiff -c $x) 2>&1 | less
         echo -n "Continue with checkin of $x? [yes] "
         read z
         case "$z" in [Nn]*) continue;; [Qq]*) exit 0;; *) ;; esac
         rcs -l $x
         ci $x
         co $x
         chmod u+w $x
         (echo "$y"; ls -l $x; cat $x) 2>&1 | less
      fi
   else
      echo "$x: No such file or directory" 1>&2
   fi
done
