#!/bin/sh
#
# $Id: checkin,v 1.5 1996/02/19 22:46:27 deven Exp $
#
# Conferencing system server -- RCS checkin script.
#
# Copyright 1994 by Deven T. Corzine.  All rights reserved.
#
# $Log: checkin,v $
# Revision 1.5  1996/02/19 22:46:27  deven
# Modified to check out first if nonexistent, and to use relative chmod.
#
# Revision 1.4  1994/04/15 22:14:25  deven
# Added stty to set erase character to backspace.
#
# Revision 1.3  1994/04/15 22:12:51  deven
# Added file name to prompt.
#
# Revision 1.2  1994/02/05 18:39:13  deven
# Added unlock and chmod to start of processing for a file.
#
# Revision 1.1  1994/01/09 05:30:36  deven
# Initial revision
#

stty erase '^h'
for x in $*; do
   if [ ! -f $x ]; then co $x; fi
   if [ -f $x ]; then
      rcs -u $x >/dev/null 2>&1
      chmod u+w $x
      if rcsdiff $x >/dev/null 2>&1; then
         echo "$x is current."
      else
         y="`ls -l $x`"
         (ls -l $x; rcsdiff -c $x) 2>&1 | less
         echo -n "Continue with checkin of $x? [yes] "
         read z
         case "$z" in [Nn]*) continue;; [Qq]*) exit 0;; *) ;; esac
         rcs -l $x
         ci $x
         co $x
         chmod u+w $x
         (echo "$y"; ls -l $x; cat $x) 2>&1 | less
      fi
   else
      echo "$x: No such file or directory" 1>&2
   fi
done
