#!/usr/bin/perl

$why = shift;
$msg = shift;

die "Usage: mailwhy </why output file> <message text>\n"
   unless $why && $msg && -r $why && -r $msg;

$HOME = $ENV{HOME};
open(IN,"<$HOME/lib/phoenix/passwd") || die "$HOME/lib/phoenix/passwd: $!\n";
while (<IN>) {
   chop;
   next if /^ *#/;
   ($user,$passwd,$reserved,$priv,@rest) = split(/:/,$_,999);
   next unless $priv;
   @email = grep(/@/,@rest);
   @rest = grep(!/@/,@rest);
   $fullname = $rest[0];
   $reserved{$user} = $reserved;
   $email{$user} = join(",",@email);
   $fullname{$user} = $fullname;
}
close(IN);

{
   local($/);
   undef $/;

   open(IN,"<$msg") || die "$msg: $!\n";
   $msg = <IN>;
   close(IN);
}

print "*** Phoenix system message follows. ***\n\n";
print $msg;
print "\n*** End of Phoenix system message. ***\n\n";

open(IN,"<$why") || die "$why: $!\n";
while (<IN>) {
   next if /^ Name {30}On Since +Idle  Away  User      FD  Priv$/;
   next if /^ ---- {30}-------- +----  ----  ----      --  ----$/;
   next unless ($detached,$name,$since,$idle,$away,$user) =
      /^(.)(.{33}) +(....[^ ]+) +([^ ]+)  (....)  ([^ ]+) /;
   $detached = ($detached eq "~");
   $name =~ s/\[.*$//;
   $name =~ s/ +$//;
   $away =~ tr/A-Z/a-z/;
   print;
   if ($user eq "guest") {
      print "*** \"$name\" is a guest user, cannot receive mail. ***\n\n";
   } elsif ($email{$user} eq "") {
      print "*** No email address known for \"$name\" ($user). ***\n\n";
   } else {
      print "*** Email to: $email{$user} ***\n\n";
      $header = "This is a Phoenix system message";
      $header .= " for $fullname{$user}" if $fullname{$user};
      $header .= ".\n\nYou are currently signed on Phoenix as \"$name\".\n";
      $header .= "Note: This is NOT your normal reserved name of " .
         "\"$reserved{$user}\".\n" unless $name eq $reserved{$user};
      $header .= "You are currently detached.  To sign back on, telnet to " .
         "the Phoenix server.\nUnder Unix, the command to do this is \"" .
         "telnet phoenix.elf.com 6789\".\n" if $detached;
      $header .= "You have been signed on since $since, and ";
      if ($idle =~ /:/) {
         $header .= "your idle time is $idle.\n\n";
         $header .= "You are currently \"$away\".  Since you have been " .
            "idle over a day, this really\nought to be listed as \"gone\" " .
            "instead.  Please try to remember to use the /gone\ncommand in " .
            "the future before you go idle if it will be a while.  Thanks!\n\n"
            if $idle =~ /d/ && $away ne "gone";
         $header .= "You are currently \"$away\".  Since you are detached " .
            "and fairly idle, this really\nought to be listed as \"gone\" " .
            "instead.  Please try to remember to use the /gone\ncommand in " .
            "the future before you go idle if it will be a while.  Thanks!\n\n"
            if $idle !~ /d/ && $away ne "gone" && $detached;
      } elsif ($idle && $idle ne "1") {
         $header .= "you have been idle for $idle minutes.\n\n";
      } elsif ($idle eq "1") {
         $header .= "you have been idle for 1 minute.\n\n";
      } else {
         $header .= "you are not idle.\n\n";
      }
      print $header;
      open(MAIL,"|/bin/mail $email{$user}") || die "/bin/mail: $!\n";
      print MAIL $header;
      print MAIL "*** Phoenix system message follows. ***\n\n";
      print MAIL $msg;
      print MAIL "\n*** End of Phoenix system message. ***\n";
      close(MAIL);
   }
}
close(IN);
