#!/bin/sh

for file in $*; do
   gpg -asb -u 7D292C9843C1453534E3854664BC257093D3B1BC $file
   chmod 644 $file $file.asc
   mv $file.asc $file.sig
done

perl -e 'foreach (@ARGV) { $t = (stat $_)[9] + 1; utime $t, $t, "$_.sig"; }' $*
