#!/bin/bash

# Check copyright notices, offer to update if necessary.
year=`date +%Y`
files=$(grep 'Copyright.*Deven.*Corzine' `find * -type f -print` | grep -v $year | grep -v 'Copyright\.\*' | sed 's/:.*//')
if [ "$files" != "" ]; then
   ls -l $files
   echo ""
   echo -n "Update copyright notices on the files above? [n] "
   read answer
   case "$answer" in
      [Yy]*) perl -i -pe 'BEGIN { $year = shift; } warn "Updating copyright notice: $ARGV\n" if s/(Copyright.*?)(-\d{4})?( Deven.*?Corzine)/$1 . (substr($1, -4) eq $year ? "" : "-$year") . $3/e' $year $files;;
   esac
fi
